### ISSUE TITLE
csrf token

### ISSUE THREAD

**Issue by karissa** [strikedebt/debtcollective-web#4]
i think they are disabled, this isn't necessarily the worst nor highly likely (other websites can sign up the current user for our mailing list) but it'd be nice to fix this as we add more user interaction

**Comment by angetran** [comment]
could you brief me on 'csrf'?

**Comment by karissa** [comment]
http://en.wikipedia.org/wiki/Cross-site_request_forgery

**Comment by karissa** [comment]
its not important until we have sign in that is separate from discourse, with cookies & functions in the walled garden.
